Lab5/Models/Datos.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;

namespace Lab5.Models
{
    public class Datos
    {
        private static Datos _ins = null;
        public static Datos ins
        {
            get
            {
                if (_ins == null) _ins = new Datos();
                return _ins;
            }
        }

        public Dictionary<string, object> Diccio = new Dictionary<string, object>();
        public Dictionary<string, bool> Diccio2 = new Dictionary<string, bool>();
        public List<Estampa> mostrar = new List<Estampa>();

        public static string[] Retornar(char[] Linea)
        {
            string[] Info = new string[3];
            string temporal = string.Empty;
            int contador = 0;

            bool comillas = false;

            for (int a = 0; a < Linea.Length; a++)
            {
                if (comillas)
                {
                    if (Linea[a] != '"')
                    {
                        temporal = temporal + Linea[a];
                    }
                    else
                    {
                        comillas = false;
                    }
                }
                else
                {
                    if (Linea[a] == '"')
                    {
                        comillas = true;
                    }
                    else if (Linea[a] == ',')
                    {
                        Info[contador] = temporal;
                        temporal = "";
                        contador++;
                    }
                    else if (Linea[a] != ',')
                    {
                        temporal = temporal + Linea[a];
                        if (a == (Linea.Length - 1))
                        {
                            Info[contador] = temporal;
                        }
                    }
                }
            }
            return Info;
        }

        public string path;
        public void GuardarArchivo(List<Estampa> Temporal)
        {
            using (var sw = new StreamWriter(path, false))
            {
                sw.WriteLine("Equipo,Jugador,Cantidad");
                foreach (var item in Temporal)
                {
                    var separar = item.nombre.Split('_');
                    sw.WriteLine($"{separar[0]},{separar[1]},{item.cantidad}");
                }
            }
        }
    }
}

Lab5/Models/Estampa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lab5.Models
{
    public class Estampa
    {
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
        [Display(Name = "Cantidad")]
        public int cantidad { get; set; }
        [Display(Name = "Disponibilidad")]
        public string dispo { get; set; }
    }
}

Lab5/Controllers/EditajeController.cs
using Lab5.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab5.Controllers
{
    public class EditajeController : Controller
    {
        // GET: Editaje
        public ActionResult Index()
        {
            foreach (var item in Datos.ins.Diccio)
            {
                var d = (Estampa)item.Value;
                var objeto = new Estampa { nombre = item.Key, cantidad = d.cantidad, dispo = d.dispo };
                Datos.ins.mostrar.Add(objeto);
            }
            Datos.ins.GuardarArchivo(Datos.ins.mostrar);
            return View(Datos.ins.mostrar);
        }
        [HttpGet]
        public ActionResult SubirArchivo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SubirArchivo(HttpPostedFileBase File)
        {
            try
            {
                if (File.ContentLength > 0 && File.FileName.EndsWith(".csv"))
                {
                    Datos.ins.Diccio.Clear();
                    Datos.ins.Diccio2.Clear();
                    Datos.ins.mostrar.Clear();
                    string _FileName = Path.GetFileName(File.FileName);
                    string _path = Path.Combine(Server.MapPath("~/Uploads"), _FileName);
                    File.SaveAs(_path);
                    ViewBag.Message = "El album se ha cargado exitosamente";
                    Datos.ins.path = _path;

                    using (var Reader = new StreamReader(_path))
                    {
                        char[] Linea = Reader.ReadLine().ToCharArray();
                        while (!Reader.EndOfStream)
                        {
                            Linea = Reader.ReadLine().ToCharArray();
                            var info = Datos.Retornar(Linea);

                            string estado = (Convert.ToInt32(info[2]) > 1) ? "Posible intercambio" : ((Convert.ToInt32(info[2]) < 1) ? "No la tiene" : "La tiene");

                            var objeto = new Estampa { cantidad = Convert.ToInt32(info[2]), dispo = estado };

                            string nombre = $"{info[0]}_{info[1]}";
                            bool disp;
                            disp = (Convert.ToInt32(info[2]) == 0) ? false : true;

                            Datos.ins.Diccio.Add(nombre, objeto);
                            Datos.ins.Diccio2.Add(nombre, disp);
                        }
                    }

                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Message = "ERROR: carga de archivo";
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Agregar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Agregar(FormCollection collection)
        {
            try
            {
                if (Datos.ins.Diccio.ContainsKey(collection["nombre"]))
                {
                    Datos.ins.mostrar.Clear();
                    var objeto = (Estampa)Datos.ins.Diccio[collection["nombre"]];
                    objeto.cantidad = objeto.cantidad + Convert.ToInt32(collection["cantidad"]);
                    objeto.dispo = (objeto.cantidad > 1) ? "Posbile intercambio" : ((objeto.cantidad < 1) ? "No la tiene" : "La tiene");
                    Datos.ins.Diccio[collection["nombre"]] = objeto;
                    Datos.ins.Diccio2[collection["nombre"]] = true;

                }
                else
                {
                    ViewBag.Message = "No es valido el dato";
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Eliminar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Eliminar(FormCollection collection)
        {
            try
            {
                if (Datos.ins.Diccio.ContainsKey(collection["nombre"]))
                {
                    Datos.ins.mostrar.Clear();
                    var objeto = (Estampa)Datos.ins.Diccio[collection["nombre"]];
                    if (objeto.cantidad >= Convert.ToInt32(collection["cantidad"]))
                    {
                        objeto.cantidad -= Convert.ToInt32(collection["cantidad"]);
                        objeto.dispo = (objeto.cantidad > 1) ? "Posible intercambio" : ((objeto.cantidad < 1) ? "No la tiene" : "La tiene");
                        Datos.ins.Diccio[collection["nombre"]] = objeto;
                        if (objeto.cantidad == 0)
                        {
                            Datos.ins.Diccio2[collection["nombre"]] = false;
                        }
                    }


                }
                else
                {
                    ViewBag.Message = "No has ingresado cantidad";
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Lab5/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab5.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lab5/Views/Editaje/Agregar.cshtml
@model Lab5.Models.Estampa

@{
    ViewBag.Title = "Agregar";
}

<h2>Obtener Estampa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Estampas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Obtener estampa" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" onclick="location.href = '@Url.Action("Index","Editaje")'">Regresar a inicio</button>
</div>

Lab5/Views/Editaje/Eliminar.cshtml
@model Lab5.Models.Estampa

@{
    ViewBag.Title = "Eliminar";
}

<h2>Vender o Cambiar Estampa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Estampas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Vender o cambiar estampa" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" onclick="location.href = '@Url.Action("Index","Editaje")'">Regresar a inicio</button>
</div>

Lab5/Views/Editaje/Index.cshtml
@model IEnumerable<Lab5.Models.Estampa>

@{
    ViewBag.Title = "Index";
}

<h2>ALBUM RUSIA 2018</h2>

<p>
    <button type="button" onclick="location.href = '@Url.Action("Agregar","Editaje")'">Obtener Estampa</button>
    <button type="button" onclick="location.href = '@Url.Action("Eliminar","Editaje")'">Vender o Intercambiar Estampa</button>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cantidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dispo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dispo)
            </td>
        </tr>
    }

</table>

Lab5/Views/Editaje/SubirArchivo.cshtml
@{
    ViewBag.Title = "SubirArchivo";
}

<h2>CARGAR ALBUM</h2>

@using (Html.BeginForm("SubirArchivo", "Editaje", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div>
        @Html.TextBox("file", "", new { type = "file" })<br />

        <input type="submit" value="Cargar archivo" />

        @ViewBag.Message

    </div>
}

Lab5/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Lab5/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Lab5/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Lab5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>